# Generated by Django 5.1.6 on 2026-09-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=20)),
                ('activity_subtype', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_name', models.CharField(max_length=150)),
                ('organizer', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('event_level', models.CharField(blank=True, max_length=20, null=True)),
                ('rank_achieved', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activities',
                'managed': False,
                
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_file', models.CharField(max_length=255)),
                ('verification_status', models.CharField(default='Pending', max_length=20)),
                ('verified_by', models.IntegerField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'certificates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('order_type', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('account_created', models.BooleanField(default=False)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'faculty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('leave_start', models.DateField()),
                ('leave_end', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('faculty_remark', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leave_applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_no', models.IntegerField()),
                ('prn', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('academic_year', models.CharField(default='2025-26', max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('branch', models.CharField(default='IT', max_length=20)),
                ('division', models.CharField(blank=True, max_length=1, null=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
